export const WORD_CATEGORIES = {
  Animals: [
    "ELEPHANT", "GIRAFFE", "PENGUIN", "DOLPHIN", "CHEETAH",
    "GORILLA", "KANGAROO", "CROCODILE", "FLAMINGO", "PLATYPUS",
    "RHINOCEROS", "PORCUPINE", "CHAMELEON", "WOLVERINE", "JAGUAR",
    "ORANGUTAN", "ARMADILLO", "PANGOLIN", "CAPYBARA", "NARWHAL",
    "AXOLOTL", "MANDRILL", "HUMMINGBIRD", "SECRETARY", "TAPIR",
  ],
  Countries: [
    "BRAZIL", "FRANCE", "JAPAN", "AUSTRALIA", "CANADA",
    "GERMANY", "INDIA", "MEXICO", "NORWAY", "PORTUGAL",
    "ARGENTINA", "THAILAND", "MOROCCO", "UKRAINE", "VIETNAM",
    "INDONESIA", "COLOMBIA", "KENYA", "ICELAND", "MALAYSIA",
    "SWITZERLAND", "BANGLADESH", "CAMBODIA", "ECUADOR", "URUGUAY",
  ],
  Fruits: [
    "MANGO", "STRAWBERRY", "BLUEBERRY", "PINEAPPLE", "WATERMELON",
    "AVOCADO", "RASPBERRY", "POMEGRANATE", "PAPAYA", "PERSIMMON",
    "CRANBERRY", "TANGERINE", "BLACKBERRY", "LYCHEE", "DRAGONFRUIT",
    "JACKFRUIT", "STARFRUIT", "GUAVA", "TAMARIND", "GOOSEBERRY",
    "ELDERBERRY", "KUMQUAT", "MULBERRY", "CANTALOUPE", "NECTARINE",
  ],
  Sports: [
    "BASKETBALL", "FOOTBALL", "CRICKET", "SWIMMING", "GYMNASTICS",
    "VOLLEYBALL", "BADMINTON", "ARCHERY", "WRESTLING", "SURFING",
    "SKATEBOARD", "FENCING", "LACROSSE", "TRIATHLON", "PARAGLIDING",
    "EQUESTRIAN", "WATERPOLO", "BIATHLON", "TAEKWONDO", "SNOOKER",
    "MARATHON", "DECATHLON", "KAYAKING", "BOBSLED", "SQUASH",
  ],
  Movies: [
    "INCEPTION", "AVATAR", "INTERSTELLAR", "TITANIC", "AVENGERS",
    "JOKER", "GLADIATOR", "PARASITE", "WHIPLASH", "ARRIVAL",
    "MEMENTO", "MOONLIGHT", "COCO", "CASABLANCA", "AMADEUS",
    "BRAVEHEART", "GOODFELLAS", "SPOTLIGHT", "OPPENHEIMER", "BARBIE",
    "SHAZAM", "ENCANTO", "RATATOUILLE", "ONWARD", "SOUL",
  ],
  Technology: [
    "ALGORITHM", "JAVASCRIPT", "DATABASE", "FRAMEWORK", "COMPILER",
    "BLOCKCHAIN", "BANDWIDTH", "PROTOCOL", "INTERFACE", "DEBUGGING",
    "SOFTWARE", "HARDWARE", "KEYBOARD", "MONITOR", "ENCRYPTION",
    "MICROCHIP", "RECURSION", "CODEBASE", "REPOSITORY", "TYPESCRIPT",
    "KUBERNETES", "TERRAFORM", "BROADBAND", "RENDERING", "FRONTEND",
  ],
  Food: [
    "SPAGHETTI", "CROISSANT", "QUESADILLA", "CHEESECAKE", "GUACAMOLE",
    "MOZZARELLA", "BRUSCHETTA", "ENCHILADA", "TIRAMISU", "FETTUCCINE",
    "GAZPACHO", "PAELLA", "STROGANOFF", "BAKLAVA", "PROSCIUTTO",
    "BURRITO", "RATATOUILLE", "SHAKSHUKA", "HUMMUS", "KIMCHI",
    "DUMPLINGS", "ANTIPASTO", "GOULASH", "SOURDOUGH", "BAGUETTE",
  ],
  Music: [
    "SYMPHONY", "SAXOPHONE", "ACCORDION", "XYLOPHONE", "TROMBONE",
    "HARPSICHORD", "SYNTHESIZER", "DRUMBEAT", "BASSLINE", "CRESCENDO",
    "ARPEGGIO", "HARMONICA", "RESONANCE", "STACCATO", "VIBRATO",
    "CONDUCTOR", "COMPOSITION", "ORCHESTRA", "CADENCE", "OVERTURE",
    "FORTISSIMO", "PIZZICATO", "COUNTERPOINT", "MODULATION", "TREMOLO",
  ],
  Space: [
    "ASTEROID", "NEBULA", "SUPERNOVA", "BLACKHOLE", "TELESCOPE",
    "SPACECRAFT", "METEORITE", "EXOPLANET", "SATELLITE", "WORMHOLE",
    "PULSAR", "QUASAR", "COSMOLOGY", "CELESTIAL", "MAGNETAR",
    "SINGULARITY", "CONSTELLATION", "ACCRETION", "PERIHELION", "APHELION",
    "GRAVITON", "ANTIMATTER", "PARALLAX", "REDSHIFT", "STARCLUSTER",
  ],
  Mythology: [
    "MINOTAUR", "CENTAUR", "PHOENIX", "PEGASUS", "BASILISK",
    "KRAKEN", "LEVIATHAN", "CHIMERA", "MEDUSA", "BEHEMOTH",
    "MANTICORE", "WYVERN", "CERBERUS", "BANSHEE", "VALKYRIE",
    "SPHINX", "CYCLOPS", "HYDRA", "DRACULA", "GOLEM",
    "TRICKSTER", "POSEIDON", "MINOTAUR", "GORGON", "SIREN",
  ],
};

export function getRandomWord() {
  const categories = Object.keys(WORD_CATEGORIES);
  const category = categories[Math.floor(Math.random() * categories.length)];
  const words = WORD_CATEGORIES[category];
  const word = words[Math.floor(Math.random() * words.length)];
  return { word, category };
}

export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
