export const WORD_CATEGORIES = {
  Animals: [
    { word: "ELEPHANT", clue: "Largest land animal with a long trunk" },
    { word: "GIRAFFE", clue: "Tallest living animal with a very long neck" },
    { word: "PENGUIN", clue: "A flightless bird that loves the cold" },
    { word: "DOLPHIN", clue: "Intelligent ocean mammal known for jumping" },
    { word: "CHEETAH", clue: "The fastest land animal on Earth" },
    { word: "GORILLA", clue: "Largest living primate found in Africa" },
    { word: "KANGAROO", clue: "Australian animal that carries babies in a pouch" },
    { word: "CROCODILE", clue: "Large reptile with powerful jaws near water" },
    { word: "FLAMINGO", clue: "Pink bird that stands on one leg" },
    { word: "PLATYPUS", clue: "Egg-laying mammal with a duck-like bill" },
    { word: "RHINOCEROS", clue: "Large herbivore with a horn on its nose" },
    { word: "PORCUPINE", clue: "Rodent covered in sharp protective quills" },
    { word: "CHAMELEON", clue: "Lizard famous for changing its color" },
    { word: "WOLVERINE", clue: "Fierce small mammal, also an X-Men character" },
    { word: "JAGUAR", clue: "Spotted big cat of the Americas" },
    { word: "ORANGUTAN", clue: "Red-haired great ape from Southeast Asia" },
    { word: "ARMADILLO", clue: "Mammal with a bony armored shell" },
    { word: "PANGOLIN", clue: "Scaly anteater and the most trafficked mammal" },
    { word: "CAPYBARA", clue: "World's largest rodent, very social" },
    { word: "NARWHAL", clue: "Arctic whale with a long spiral tusk" },
    { word: "AXOLOTL", clue: "Mexican salamander that can regrow limbs" },
    { word: "HUMMINGBIRD", clue: "Tiny bird that can hover and fly backwards" },
    { word: "OCTOPUS", clue: "Sea creature with eight arms and three hearts" },
    { word: "SEAHORSE", clue: "Ocean fish where the male carries babies" },
    { word: "BUTTERFLY", clue: "Insect that transforms from a caterpillar" },
  ],
  Countries: [
    { word: "BRAZIL", clue: "Largest country in South America, famous for carnival" },
    { word: "FRANCE", clue: "European nation home to the Eiffel Tower" },
    { word: "JAPAN", clue: "Island nation known for sushi and cherry blossoms" },
    { word: "AUSTRALIA", clue: "Country that is also a continent" },
    { word: "CANADA", clue: "Second largest country, known for maple syrup" },
    { word: "GERMANY", clue: "European country famous for Oktoberfest" },
    { word: "INDIA", clue: "Home to the Taj Mahal and over a billion people" },
    { word: "MEXICO", clue: "Country famous for tacos and ancient pyramids" },
    { word: "NORWAY", clue: "Scandinavian land of fjords and northern lights" },
    { word: "PORTUGAL", clue: "Western European country that borders Spain" },
    { word: "ARGENTINA", clue: "South American country famous for tango" },
    { word: "THAILAND", clue: "Southeast Asian kingdom known as the Land of Smiles" },
    { word: "MOROCCO", clue: "North African country with Sahara desert edges" },
    { word: "ICELAND", clue: "Nordic island nation with volcanoes and geysers" },
    { word: "SWITZERLAND", clue: "Mountainous European country famous for chocolate" },
    { word: "EGYPT", clue: "Land of pharaohs, pyramids, and the Nile" },
    { word: "GREECE", clue: "Birthplace of democracy and the Olympic Games" },
    { word: "KENYA", clue: "East African country famous for safaris" },
    { word: "VIETNAM", clue: "Southeast Asian country known for pho soup" },
    { word: "PERU", clue: "South American home of Machu Picchu" },
    { word: "TURKEY", clue: "Country bridging Europe and Asia, home to Istanbul" },
    { word: "CUBA", clue: "Caribbean island nation known for classic cars" },
    { word: "NEPAL", clue: "Himalayan country that contains Mount Everest" },
    { word: "IRELAND", clue: "The Emerald Isle, famous for shamrocks" },
    { word: "COLOMBIA", clue: "South American country named after Columbus" },
  ],
  Fruits: [
    { word: "MANGO", clue: "Tropical fruit called the king of fruits" },
    { word: "STRAWBERRY", clue: "Small red fruit with seeds on the outside" },
    { word: "BLUEBERRY", clue: "Tiny blue superfood, great in smoothies" },
    { word: "PINEAPPLE", clue: "Tropical fruit with a spiky crown on top" },
    { word: "WATERMELON", clue: "Large green fruit that is mostly water inside" },
    { word: "AVOCADO", clue: "Creamy green fruit used in guacamole" },
    { word: "POMEGRANATE", clue: "Red fruit filled with jewel-like seeds" },
    { word: "PAPAYA", clue: "Tropical orange-fleshed fruit with black seeds" },
    { word: "CRANBERRY", clue: "Tart red berry popular during Thanksgiving" },
    { word: "TANGERINE", clue: "Small sweet citrus fruit, easy to peel" },
    { word: "BLACKBERRY", clue: "Dark purple berry that grows on thorny bushes" },
    { word: "LYCHEE", clue: "Sweet Asian fruit with a rough pink shell" },
    { word: "DRAGONFRUIT", clue: "Exotic pink fruit with white spotted flesh" },
    { word: "JACKFRUIT", clue: "World's largest tree fruit, can taste like pulled pork" },
    { word: "COCONUT", clue: "Tropical fruit with water inside and a hard shell" },
    { word: "GUAVA", clue: "Tropical fruit that is pink or white inside" },
    { word: "RASPBERRY", clue: "Soft, hollow red berry that falls apart easily" },
    { word: "CHERRY", clue: "Small round fruit often on top of sundaes" },
    { word: "PEACH", clue: "Fuzzy soft fruit with a large pit inside" },
    { word: "KIWI", clue: "Fuzzy brown fruit that is bright green inside" },
    { word: "GRAPE", clue: "Small fruit that grows in clusters on vines" },
    { word: "APRICOT", clue: "Small orange fruit similar to a peach" },
    { word: "KUMQUAT", clue: "Tiny citrus fruit you eat whole, skin and all" },
    { word: "CANTALOUPE", clue: "Melon with orange flesh and netted skin" },
    { word: "NECTARINE", clue: "Smooth-skinned cousin of the peach" },
  ],
  Sports: [
    { word: "BASKETBALL", clue: "Sport where you shoot a ball through a hoop" },
    { word: "FOOTBALL", clue: "World's most popular sport, aka soccer" },
    { word: "CRICKET", clue: "Bat-and-ball game huge in India and England" },
    { word: "SWIMMING", clue: "Olympic sport performed in water" },
    { word: "GYMNASTICS", clue: "Sport with flips, balance beams, and rings" },
    { word: "VOLLEYBALL", clue: "Team sport where you hit a ball over a net" },
    { word: "BADMINTON", clue: "Racquet sport played with a shuttlecock" },
    { word: "ARCHERY", clue: "Sport of shooting arrows at a target" },
    { word: "WRESTLING", clue: "Ancient combat sport of grappling opponents" },
    { word: "SURFING", clue: "Riding ocean waves while standing on a board" },
    { word: "SKATEBOARD", clue: "Riding and doing tricks on a four-wheeled board" },
    { word: "FENCING", clue: "Sword fighting as an Olympic sport" },
    { word: "LACROSSE", clue: "Team sport using sticks with nets to catch a ball" },
    { word: "TRIATHLON", clue: "Endurance race combining swim, bike, and run" },
    { word: "MARATHON", clue: "Long-distance running race of 26.2 miles" },
    { word: "BOXING", clue: "Combat sport fought with gloved fists in a ring" },
    { word: "TENNIS", clue: "Racquet sport played on a court with a net" },
    { word: "BASEBALL", clue: "America's pastime with bats, balls, and bases" },
    { word: "SNOWBOARD", clue: "Winter sport of sliding down slopes on a board" },
    { word: "KARATE", clue: "Japanese martial art meaning empty hand" },
    { word: "ROWING", clue: "Water sport of propelling a boat with oars" },
    { word: "HOCKEY", clue: "Fast ice sport played with sticks and a puck" },
    { word: "CLIMBING", clue: "Sport of ascending walls or mountains" },
    { word: "DIVING", clue: "Olympic sport of jumping into water artistically" },
    { word: "GOLF", clue: "Sport of hitting a ball into holes on a course" },
  ],
  Food: [
    { word: "SPAGHETTI", clue: "Long thin Italian pasta, often with tomato sauce" },
    { word: "CROISSANT", clue: "Flaky, buttery French crescent-shaped pastry" },
    { word: "QUESADILLA", clue: "Mexican tortilla filled with melted cheese" },
    { word: "CHEESECAKE", clue: "Creamy dessert with a graham cracker crust" },
    { word: "GUACAMOLE", clue: "Mexican dip made from mashed avocados" },
    { word: "BRUSCHETTA", clue: "Italian appetizer with tomatoes on toasted bread" },
    { word: "TIRAMISU", clue: "Italian coffee-flavored layered dessert" },
    { word: "PAELLA", clue: "Spanish rice dish with seafood and saffron" },
    { word: "BAKLAVA", clue: "Sweet pastry made of layers, nuts, and honey" },
    { word: "BURRITO", clue: "Mexican flour tortilla wrapped around filling" },
    { word: "RATATOUILLE", clue: "French vegetable stew from Provence" },
    { word: "HUMMUS", clue: "Middle Eastern dip made from chickpeas" },
    { word: "KIMCHI", clue: "Korean fermented spicy cabbage side dish" },
    { word: "DUMPLINGS", clue: "Small pockets of dough filled with meat or veggies" },
    { word: "SOURDOUGH", clue: "Bread made with naturally fermented starter" },
    { word: "BAGUETTE", clue: "Long thin French bread with a crispy crust" },
    { word: "SUSHI", clue: "Japanese dish of vinegared rice and raw fish" },
    { word: "PANCAKE", clue: "Flat round breakfast cake cooked on a griddle" },
    { word: "LASAGNA", clue: "Italian baked pasta with layers of cheese and sauce" },
    { word: "PRETZEL", clue: "Twisted baked bread snack, often salted" },
    { word: "SAMOSA", clue: "Indian fried pastry filled with spiced potatoes" },
    { word: "WAFFLE", clue: "Grid-patterned breakfast food, great with syrup" },
    { word: "FONDUE", clue: "Swiss dish of melted cheese for dipping bread" },
    { word: "EMPANADA", clue: "Stuffed pastry that is baked or fried" },
    { word: "TZATZIKI", clue: "Greek yogurt sauce with cucumber and garlic" },
  ],
  Space: [
    { word: "ASTEROID", clue: "Rocky object orbiting the Sun, smaller than a planet" },
    { word: "NEBULA", clue: "Giant cloud of gas and dust where stars are born" },
    { word: "SUPERNOVA", clue: "Explosive death of a massive star" },
    { word: "BLACKHOLE", clue: "Region in space where nothing can escape" },
    { word: "TELESCOPE", clue: "Instrument used to observe distant objects in space" },
    { word: "SPACECRAFT", clue: "Vehicle designed for traveling through space" },
    { word: "METEORITE", clue: "Space rock that survives entry and lands on Earth" },
    { word: "SATELLITE", clue: "Object that orbits a planet, natural or man-made" },
    { word: "CONSTELLATION", clue: "Pattern of stars forming a recognizable shape" },
    { word: "ECLIPSE", clue: "When one celestial body blocks another" },
    { word: "GALAXY", clue: "Massive system of billions of stars" },
    { word: "GRAVITY", clue: "Force that attracts objects toward each other" },
    { word: "COMET", clue: "Icy body that develops a bright tail near the Sun" },
    { word: "MERCURY", clue: "Smallest and closest planet to the Sun" },
    { word: "SATURN", clue: "Planet famous for its beautiful rings" },
    { word: "JUPITER", clue: "Largest planet in our solar system" },
    { word: "NEPTUNE", clue: "Blue ice giant, the farthest known planet" },
    { word: "ASTRONAUT", clue: "Person trained to travel and work in space" },
    { word: "ORBIT", clue: "The curved path an object takes around another" },
    { word: "COSMOS", clue: "Another word for the universe as a whole" },
    { word: "LUNAR", clue: "Relating to the Moon" },
    { word: "PLASMA", clue: "Fourth state of matter, found in stars" },
    { word: "QUASAR", clue: "Extremely bright center of a distant galaxy" },
    { word: "PULSAR", clue: "Rapidly spinning neutron star emitting beams" },
    { word: "VENUS", clue: "Second planet from the Sun, hottest in our system" },
  ],
  Science: [
    { word: "MOLECULE", clue: "Smallest unit of a chemical compound" },
    { word: "PHOTOSYNTHESIS", clue: "Process plants use to convert sunlight into food" },
    { word: "ELECTRON", clue: "Negatively charged subatomic particle" },
    { word: "CHROMOSOME", clue: "Thread-like structure carrying genetic DNA" },
    { word: "BACTERIA", clue: "Microscopic single-celled organisms" },
    { word: "NUCLEUS", clue: "Central core of an atom or cell" },
    { word: "EVOLUTION", clue: "Process of species changing over generations" },
    { word: "MAGNETISM", clue: "Force produced by moving electric charges" },
    { word: "DINOSAUR", clue: "Extinct reptiles that ruled Earth millions of years ago" },
    { word: "VACCINE", clue: "Substance that stimulates immunity against disease" },
    { word: "OXYGEN", clue: "Gas essential for breathing, 21 percent of our air" },
    { word: "VITAMIN", clue: "Organic nutrients essential for body functions" },
    { word: "TSUNAMI", clue: "Massive ocean wave caused by underwater earthquakes" },
    { word: "VOLCANO", clue: "Mountain that erupts with lava and ash" },
    { word: "TORNADO", clue: "Violently rotating column of air touching the ground" },
    { word: "GLACIER", clue: "Massive slow-moving body of ice on land" },
    { word: "FOSSIL", clue: "Preserved remains of ancient living things" },
    { word: "PROTEIN", clue: "Large molecules essential for building body tissue" },
    { word: "ELEMENT", clue: "Pure substance made of only one type of atom" },
    { word: "NEUTRON", clue: "Uncharged particle found in an atomic nucleus" },
    { word: "SPECTRUM", clue: "The range of colors visible in light" },
    { word: "PRISM", clue: "Glass shape that splits white light into rainbow" },
    { word: "CATALYST", clue: "Substance that speeds up a chemical reaction" },
    { word: "ENTROPY", clue: "Measure of disorder in a system" },
    { word: "GENOME", clue: "Complete set of DNA in an organism" },
  ],
  History: [
    { word: "PYRAMID", clue: "Ancient Egyptian monumental tomb structure" },
    { word: "GLADIATOR", clue: "Ancient Roman fighter who battled in arenas" },
    { word: "SAMURAI", clue: "Elite Japanese warrior class with swords" },
    { word: "PHARAOH", clue: "Title of ancient Egyptian rulers" },
    { word: "COLOSSEUM", clue: "Iconic ancient Roman amphitheater in Rome" },
    { word: "RENAISSANCE", clue: "European cultural rebirth of art and learning" },
    { word: "CRUSADE", clue: "Medieval religious military expedition to the Holy Land" },
    { word: "EMPEROR", clue: "Ruler of an empire, highest monarch" },
    { word: "DYNASTY", clue: "Succession of rulers from the same family" },
    { word: "REVOLUTION", clue: "Forceful overthrow of a government or system" },
    { word: "MEDIEVAL", clue: "Period of the Middle Ages in European history" },
    { word: "SPARTAN", clue: "Ancient Greek warrior known for extreme discipline" },
    { word: "ARTIFACT", clue: "Object made by humans from an earlier time" },
    { word: "MONARCHY", clue: "Form of government ruled by a king or queen" },
    { word: "VIKING", clue: "Norse seafarers who raided and traded across Europe" },
    { word: "CHARIOT", clue: "Ancient two-wheeled horse-drawn vehicle for war" },
    { word: "CATHEDRAL", clue: "Large and important church, often Gothic" },
    { word: "KNIGHT", clue: "Armored medieval warrior who fought on horseback" },
    { word: "EMPIRE", clue: "Large territory ruled by a single authority" },
    { word: "SULTAN", clue: "Muslim sovereign ruler of the Ottoman Empire" },
    { word: "HIEROGLYPH", clue: "Ancient Egyptian picture-based writing symbol" },
    { word: "TROJAN", clue: "Related to the ancient city of Troy and its famous war" },
    { word: "LEGION", clue: "Large unit of the Roman army" },
    { word: "CLEOPATRA", clue: "Famous last active ruler of ancient Egypt" },
    { word: "SHOGUN", clue: "Military dictator of feudal Japan" },
  ],
};

export function getRandomWord() {
  const categories = Object.keys(WORD_CATEGORIES);
  const category = categories[Math.floor(Math.random() * categories.length)];
  const items = WORD_CATEGORIES[category];
  const item = items[Math.floor(Math.random() * items.length)];
  return { word: item.word, category, clue: item.clue };
}

export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
